import React from "react";

const ReferralPolicy: React.FC = () => {
  return (
    <div className="w-full px-4 mx-auto max-w-screen-md sm:px-6 lg:px-8 py-16">
      <h1 className="text-2xl sm:text-3xl max-sm:mt-10  uppercase font-extrabold tracking-tight">
        Earn with Genomac Platform
      </h1>

      <p className="text-sm text-gray-600 mt-2">
        Last updated: October 28, 2025
      </p>

      <div className="mt-6 space-y-6 text-xs sm:text-sm md:text-base text-gray-800 leading-6">
        <p>
          This Referral Policy (“Policy”) outlines the terms and conditions
          governing the referral program operated by Genomac Innovation Hub
          (“G-iHub”, “We”, “Us”, or “Our”) under its Earn with Genomac
          initiative.
        </p>
        <p>
          By participating in this referral program, you (“Referrer” or
          “Participant”) agree to comply with this Policy, our Terms of Use, and
          Privacy Policy.
        </p>

        <section>
          <h2 className="font-semibold text-lg">1. Purpose</h2>
          <p>
            The Earn with Genomac Referral Program (“Program”) is designed to
            reward registered users who refer others to participate in G-iHub’s
            digital training, innovation challenges, incubation opportunities,
            or paid programs. This Policy ensures transparency, fairness, and
            accountability in how referrals and rewards are managed.
          </p>
        </section>

        <section>
          <h2 className="font-semibold text-lg">2. Eligibility</h2>
          <ul className="list-disc ml-6 space-y-2">
            <li>Have a verified account on the G-iHub platform.</li>
            <li>Be at least 18 years old.</li>
            <li>Comply with all platform rules and community standards.</li>
            <li>
              Not be suspended, banned, or under investigation for fraudulent
              activity.
            </li>
          </ul>
          <p className="mt-3">
            Referrals are only valid for new users who have not previously
            registered or engaged with G-iHub under any other account.
          </p>
        </section>

        <section>
          <h2 className="font-semibold text-lg">
            3. How the Referral Program Works
          </h2>
          <ol className="list-decimal ml-6 space-y-4">
            <li>
              <p className="font-medium">Unique Referral Link:</p>
              <ul className="list-disc ml-6 space-y-2">
                <li>
                  Each registered user receives a unique referral link or code
                  generated by the system.
                </li>
                <li>
                  This link is to be shared responsibly through social networks,
                  emails, or other personal communication channels.
                </li>
              </ul>
            </li>
            <li>
              <p className="font-medium">Successful Referral:</p>
              <p className="mt-1">
                A referral is considered successful when a new user registers on
                the platform using your referral link or code and meets one or
                more of the following conditions:
              </p>
              <ul className="list-disc ml-6 space-y-2 mt-2">
                <li>Completes registration and verification.</li>
                <li>
                  Enrolls and pays for the program
                  specified in this case the Computational Biology Bootcamp.
                </li>
                <li>
                  Participates actively in innovation or incubation activities.
                </li>
                <li>
                  Earns or contributes to the “Earn with Genomac” ecosystem.
                </li>
              </ul>
            </li>
            <li>
              <p className="font-medium">Reward or Commission:</p>
              <ul className="list-disc ml-6 space-y-2">
                <li>
                  Rewards may be monetary, service credits, or access to premium
                  opportunities.
                </li>
                <li>
                  The specific value or percentage of commission will be clearly
                  stated in the program dashboard or promotional materials.
                </li>
                <li>
                  G-iHub reserves the right to adjust the reward structure at
                  any time, with notice to participants.
                </li>
              </ul>
            </li>
          </ol>
        </section>

        <section>
          <h2 className="font-semibold text-lg">
            4. Referral Payment and Payouts
          </h2>
          <ul className="list-disc ml-6 space-y-2">
            <li>
              Payment Schedule: Rewards are processed monthly or according to
              the schedule published on the platform.
            </li>
            <li>
              Payment Method: Commissions are paid via bank transfer, digital
              wallet, or another approved payment channel.
            </li>
            <li>
              Verification: Payments are subject to verification of referred
              user activity and compliance.
            </li>
            <li>
              Minimum Payout Threshold: A minimum balance may be required before
              withdrawals are permitted. This amount will be stated on the
              program portal.
            </li>
            <li>
              Taxes: Participants are responsible for reporting and paying any
              applicable taxes or fees in their jurisdiction.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="font-semibold text-lg">5. Prohibited Activities</h2>
          <p>Participants agree not to:</p>
          <ul className="list-disc ml-6 space-y-2 mt-2">
            <li>
              Engage in spamming, unsolicited messages, or misleading
              advertising to promote referral links.
            </li>
            <li>
              Create multiple fake or duplicate accounts to earn commissions.
            </li>
            <li>
              Misrepresent G-iHub’s programs, services, or payment structure.
            </li>
            <li>
              Use paid advertising that impersonates G-iHub or misuses its
              trademarks.
            </li>
            <li>
              Refer individuals without their consent or in violation of data
              privacy laws.
            </li>
          </ul>
          <p className="mt-3">
            Violations of these rules may result in account suspension, loss of
            rewards, or permanent termination from the Program.
          </p>
        </section>

        <section>
          <h2 className="font-semibold text-lg">
            6. Program Integrity and Fraud Prevention
          </h2>
          <p>
            G-iHub monitors all referral activities for authenticity and
            compliance. We reserve the right to:
          </p>
          <ul className="list-disc ml-6 space-y-2 mt-2">
            <li>Audit referral activities at any time.</li>
            <li>Delay or withhold payments pending investigation.</li>
            <li>
              Revoke rewards obtained through fraudulent, deceptive, or
              unethical behavior.
            </li>
          </ul>
          <p className="mt-3">
            Our decision regarding suspected fraud or abuse shall be final and
            binding.
          </p>
        </section>

        <section>
          <h2 className="font-semibold text-lg">
            7. Modifications to the Program
          </h2>
          <p>
            G-iHub reserves the right to modify, pause, or terminate the
            Referral Program at any time without prior notice. Changes may
            include reward structure, eligibility, or payout timelines.
          </p>
          <p className="mt-2">
            Participants will be notified via email or dashboard updates when
            significant changes occur.
          </p>
        </section>

        <section>
          <h2 className="font-semibold text-lg">8. Limitation of Liability</h2>
          <p>
            G-iHub shall not be liable for any indirect, incidental, or
            consequential damages resulting from:
          </p>
          <ul className="list-disc ml-6 space-y-2 mt-2">
            <li>
              Delay or failure in referral tracking or payment due to system
              errors.
            </li>
            <li>Unauthorized access to user accounts.</li>
            <li>
              Acts or omissions beyond our reasonable control (e.g., network
              downtime, payment processor failures).
            </li>
          </ul>
        </section>

        <section>
          <h2 className="font-semibold text-lg">
            9. Data Protection and Privacy
          </h2>
          <p>
            All referral data (names, emails, referral counts, and payment
            records) are handled in accordance with our Privacy Policy and
            compliant with both Nigeria Data Protection Regulation (NDPR) and
            General Data Protection Regulation (GDPR) for international users.
          </p>
          <p className="mt-2">
            We do not sell or share personal referral data with unauthorized
            third parties.
          </p>
        </section>

        <section>
          <h2 className="font-semibold text-lg">10. Dispute Resolution</h2>
          <p>
            Any disputes or claims related to this Program will first be
            addressed internally by G-iHub’s support team. If unresolved, such
            disputes shall be governed by the laws of the Federal Republic of
            Nigeria, and parties agree to the exclusive jurisdiction of Nigerian
            courts.
          </p>
        </section>

        <section>
          <h2 className="font-semibold text-lg">11. Contact Information</h2>
          <ul className="list-disc ml-6 space-y-2">
            <li>By email: genomacinnovationhub@gmail.com</li>
            <li>
              By visiting:{" "}
              <a
                href="https://www.genomacinnovationhub.com/contact"
                className="text-orange-600 underline"
                target="_blank"
                rel="noreferrer"
              >
                https://www.genomacinnovationhub.com/contact
              </a>
            </li>
          </ul>
        </section>
      </div>
    </div>
  );
};

export default ReferralPolicy;